// COMMENTS REDUCER

export const GET_COMMENTS_FULFILLED = "GET/COMMENTS/FULFILLED"
export const GET_COMMENTS_PENDING = "GET/COMMENTS/PENDING"
export const GET_COMMENTS_REJECTED = "GET/COMMENTS/REJECTED"

export const ADD_COMMENTS_FULFILLED = "ADD_COMMENTS_FULFILLED"
export const ADD_COMMENTS_PENDING = "ADD_COMMENTS_PENDING"
export const ADD_COMMENTS_REJECTED = "ADD_COMMENTS_REJECTED"


// NEWS REDUCER

export const GET_NEWS_FULFILLED = "GET_NEWS_FULFILLED"
export const GET_NEWS_PENDING = "GET_NEWS_PENDING"
export const GET_NEWS_REJECTED = "GET_NEWS_REJECTED"

export const TEXT = "TEXT"

export const FINDBYID_NEWS_FULFILLED = "FINDBYID_NEWS_FULFILLED"
export const FINDBYID_NEWS_PENDING = "FINDBYID_NEWS_PENDING"
export const FINDBYID_NEWS_REJECTED = "FINDBYID_NEWS_REJECTED"

export const FINDBYID_NEWS_CATEGORIES_FULFILLED = "FINDBYID_NEWS_CATEGORIES_FULFILLED"
export const FINDBYID_NEWS_CATEGORIES_PENDING = "FINDBYID_NEWS_CATEGORIES_PENDING"
export const FINDBYID_NEWS_CATEGORIES_REJECTED = "FINDBYID_NEWS_CATEGORIES_REJECTED"

// CATEGORIES REDUCER

export const CATEGORIESREMOVE = "CATEGORIESREMOVE"
export const CATEGORIES_BLOCK = "CATEGORIES_BLOCK"

export const GET_CATEGORIES_FULFILLED = "GET_CATEGORIES_FULFILLED"
export const GET_CATEGORIES_PENDING = "GET_CATEGORIES_PENDING"
export const GET_CATEGORIES_REJECTED = "GET_CATEGORIES_REJECTED"




// USERS REDUCER

export const REGISTRATION_USERS_FULFILLED = "REGISTRATION_USERS_FULFILLED"
export const REGISTRATION_USERS_PENDING = "REGISTRATION_USERS_PENDING"
export const REGISTRATION_USERS_REJECTED = "REGISTRATION_USERS_REJECTED"

export const LOGIN_USERS_FULFILLED = "LOGIN_USERS_FULFILLED"
export const LOGIN_USERS_PENDING = "LOGIN_USERS_PENDING"
export const LOGIN_USERS_REJECTED = "LOGIN_USERS_REJECTED"

export const REMOVE = "REMOVE"
export const REGISTRATION = "REGISTRATION"

export const FINDBYID_USERS_FULFILLED = "FINDBYID_USERS_FULFILLED"
export const FINDBYID_USERS_PENDING = "FINDBYID_USERS_PENDING"
export const FINDBYID_USERS_REJECTED = "FINDBYID_USERS_REJECTED"

export const GET_USERS_FULFILLED = "GET/USERS/FULFILLED"
export const GET_USERS_PENDING = "GET/USERS/PENDING"
export const GET_USERS_REJECTED = "GET/USERS/REJECTED"

export const USERS = "USERS"
